### ISSUE TITLE
Can Not Install

### ISSUE THREAD

**Issue by nicolas-miari** [lhagan/ShellHere#1]
As of macOS 10.12.6 (at least), the Finder toolbar does not accept dragging and dropping the app. 

Is there a workaround?

**Comment by lhagan** [comment]
I'm actually no longer using macOS so I can't test this at the moment, but it looks like you need to CMD drag to the toolbar. Let me know if this works and I'll update the readme.

> Add a file or an app: Press and hold the Command key, then drag the item to the Finder toolbar until you see a green plus sign.

Source: https://support.apple.com/kb/PH25527?locale=en_US

**Comment by nicolas-miari** [comment]
Yes, you are right! It's working perfectly now, thanks.
